# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94807a34ef7d36f2abfbcf5c7475aabf23507d968aadef996d4fe4df7d95f650402e16be190101ddfbbccfa3d64b7053d8bdc47255839c27e511856f67241706

test:
  secret_key_base: d39016924d643d4c15c12788cc45494058a2a713e8ec6ff38470852a18314179a92553d3b6ce29faa016cece546c316096f3add18154872f9310219b653baec2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
